id: 739dcc89a6e74a5ba1e5da93b3ef5678
initial_creation_type: TMX
origin_type: null
source_metadata:
  id: ''
  title: Toh_179-Teaching_The_Relative_and_Ultimate_Truths-v1
  language: en
  author: ''
  volume: {}
